### ISSUE TITLE
Configuration management crate

### ISSUE THREAD

**Issue by mhfowler** [peachcloud/peach-lib#13]
soon after starting, I needed to add a new key and value to the dyndns config. 
This brought up the question of migrations of configs (even using yaml). 

I think ideally, if a value is not found in the config.yml, it doesn't crash, it just uses a programmatically declared default instead.  We could still do migrations if needed, but this means the fallback is more flexible and most things may not require a migration (if they are just adding or removing fields). 

To achieve this, it seems like maybe using a Configuration management crate might be the easiest. These let you pretty easily set a default for when a config is not found, and don't crash when the config is not found.

Two possibilities:
- https://lib.rs/crates/config
- https://docs.rs/figment/0.10.5/figment/  (this one is used by the upcoming rocket 0.5)

cc @mycognosist

**Comment by mhfowler** [comment]
just directly deserializing yaml into a type, like I was doing initiailly, means the software crashes whenever a field is not found. Or you can specify every field as an Option type ... but this might be a bit messy when really what we want is a default value, not just an option.

**Comment by mhfowler** [comment]
I found that there is a way to specify a default value in Serde alone, 
but in classic rust fashion, the new better syntax for it has an open PR which is not yet merged 

the current syntax is kind of awkward and you need to declare a separate function for every default
```
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct PeachDynDnsConfig {
    pub domain: String,
    pub dns_server_address: String,
    pub tsig_key_path: String,
    #[serde(default = "enabled_default")]
    pub enabled: bool,
}

pub fn enabled_default() -> bool {
    false
}```

**Comment by mhfowler** [comment]
serde PR https://github.com/serde-rs/serde/pull/1490

**Comment by mycognosist** [comment]
@mhfowler 

Using the serde deserialization default option feels like a more efficient and ergonomic solution than requiring a config management crate. Having to define a function to return the default value is a bit cumbersome but at least it's just three lines of code.

> you need to declare a separate function for every default

Really? This is really surprising to me!

> soon after starting, I needed to add a new key and value to the dyndns config.

Do you foresee this situation arising once the library is ready for production? In other words, is it likely that additional config options will need to be added once it's all working? You know this DNS stuff way better than I do. Unfortunately I don't really have a satisfactory answer or idea for config / migration management, though the serde default value option seems like a reasonable stopgap to me.

**Comment by mhfowler** [comment]
I think the configurations for dyndns will stabilize relatively soon, but I foresee that if there is one primary configuration file, it would be frustrating if making a change to peach-web somewhere, to add a new configuration, could inadvertently break peach-dyndns because peach-dyndns can no longer deserialize the configuration file, and vice versa, which is why I wanted to put a little extra thought into making it a bit more robust. 

I found there is a "default" attribute which you can use quite simply, as long as you don't specify what the default value should be. This is what I've implemented here https://github.com/peachcloud/peach-lib/pull/14/files#diff-b4ff6117faa2dcbab7bc34d69b28d3245c1669aa74f37a8e587ed9081c3ba3ddR20

maybe in the future Serde will finish the PR that I linked to which would allow for specifying these values without the use of a function ... and in the meantime, when we need to, using a function also works

**Comment by mycognosist** [comment]
> I found there is a "default" attribute which you can use quite simply, as long as you don't specify what the default value should be

Nice. Seems like a solid approach.

> if there is one primary configuration file, it would be frustrating if making a change to peach-web somewhere, to add a new configuration, could inadvertently break peach-dyndns because peach-dyndns can no longer deserialize the configuration file, and vice versa, which is why I wanted to put a little extra thought into making it a bit more robust

Roger that, good thinking. I think the approach you've taken by bundling this functionality into `peach-lib` will help to prevent these sorts of inadvertent breakages. Having the default values for extra robustness is a smart move.

**Comment by mhfowler** [comment]
Closing this as serde seems to be working well for now. 

Also just succesfully installed all the work I'd been doing to my peachcloud remotely, using peach-config update... cool
